/**
 * Compiles tokens/tokens.ts into:
 *   - src/styles/tokens.css
 *   - registry.json (the "theme" + font items, plus one item per
 *     src/components/ui/*.tsx, with deps inferred from imports)
 *
 * Usage: REGISTRY_URL=https://detent.example.com/r npm run tokens
 *        npm run tokens -- --strict   (CI: fail on contrast or palette problems in any preset)
 */
import { readdirSync, readFileSync, writeFileSync, mkdirSync } from "node:fs"
import path from "node:path"
import { CHART, FONTS, PRESETS, base, brand, createTokens, tokensToCss, utilities } from "../tokens/tokens.ts"
import { auditContrast } from "../tokens/contrast.ts"
import { validatePalette } from "../tokens/palette.ts"

const ROOT = path.resolve(import.meta.dirname, "..")
const REGISTRY_NAME = "detent"
const REGISTRY_URL = (process.env.REGISTRY_URL ?? "http://localhost:5173/r").replace(/\/$/, "")

const tokens = createTokens(brand)
const { root, light, dark, effects, theme } = tokens

const lightKeys = Object.keys(light).sort()
const darkKeys = Object.keys(dark).sort()
if (lightKeys.join() !== darkKeys.join()) {
  const missing = lightKeys.filter((k) => !(k in dark)).concat(darkKeys.filter((k) => !(k in light)))
  throw new Error(`Light/dark token mismatch: ${missing.join(", ")}`)
}
if (Object.keys(effects.light).sort().join() !== Object.keys(effects.dark).sort().join()) {
  throw new Error("Light/dark material effects mismatch")
}

// Locally, warn (don't fail) so a brand can be explored before it's tuned.
// With --strict (CI), every preset must pass and the chart palette must
// validate on each preset's card surface.
const strict = process.argv.includes("--strict")
const problems: string[] = []
const audited = strict ? Object.values(PRESETS) : [brand]
for (const b of audited) {
  const t = createTokens(b)
  for (const theme of ["light", "dark"] as const) {
    for (const r of auditContrast(t[theme]).filter((r) => !r.pass)) {
      problems.push(`contrast [${b.name}/${theme}] ${r.use}: ${r.fg} on ${r.bg} is ${r.ratio.toFixed(2)}:1 (needs ${r.min}:1)`)
    }
    if (strict) {
      const report = validatePalette(CHART[theme], theme, t[theme].card)
      for (const f of report.failures) problems.push(`chart palette [${b.name}/${theme}] ${f}`)
    }
  }
}
for (const p of problems) console.warn(`⚠ ${p}`)
if (strict) {
  if (problems.length) {
    console.error(`✗ ${problems.length} contrast/palette problem(s) across ${audited.length} presets`)
    process.exit(1)
  }
  console.log(`✓ contrast and chart palette pass for ${audited.length} presets × 2 themes`)
}

// --- CSS output ------------------------------------------------------------
type Rules = { [prop: string]: string | Rules }
const rules = (sel: string, r: Rules, indent: string): string =>
  `${indent}${sel} {\n${Object.entries(r)
    .map(([k, v]) =>
      typeof v === "object"
        ? rules(k, v, indent + "  ")
        : k.startsWith("@apply")
          ? `${indent}  ${k};`
          : `${indent}  ${k}: ${v};`,
    )
    .join("\n")}\n${indent}}`

const css = `/* Generated by scripts/build-tokens.ts from the "${brand.name}" brand — edit tokens/tokens.ts instead. */

@custom-variant dark (&:is(.dark *));

@theme inline {
${Object.entries(theme)
  .map(([k, v]) => `  --${k}: ${v};`)
  .join("\n")}
}

${tokensToCss(tokens)}

:root { color-scheme: light; }
.dark { color-scheme: dark; }

@layer base {
${Object.entries(base)
  .map(([sel, r]) => rules(sel, r, "  "))
  .join("\n")}
}

${Object.entries(utilities)
  .map(([name, r]) => rules(`@utility ${name}`, r, ""))
  .join("\n\n")}
`
mkdirSync(path.join(ROOT, "src/styles"), { recursive: true })
writeFileSync(path.join(ROOT, "src/styles/tokens.css"), css)

// --- registry.json ---------------------------------------------------------
// shadcn's registry format writes `@apply x` as a key with an empty object.
const toRegistryCss = (r: Rules): Record<string, unknown> =>
  Object.fromEntries(
    Object.entries(r).map(([k, v]) => [k, typeof v === "object" ? toRegistryCss(v) : k.startsWith("@apply") ? {} : v]),
  )

const itemUrl = (name: string) => `${REGISTRY_URL}/${name}.json`

const FONT_VARIABLE = { ui: "--font-ui", mono: "--font-code", display: "--font-display" } as const
const fonts = (Object.entries(brand.type) as [keyof typeof FONT_VARIABLE, keyof typeof FONTS][]).map(
  ([role, id]) => {
    const f = FONTS[id]
    return {
      name: `font-${role}`,
      type: "registry:font",
      title: `${f.google.replace(/_/g, " ")} (${role})`,
      font: {
        family: f.family,
        provider: "google",
        import: f.google,
        variable: FONT_VARIABLE[role],
        subsets: ["latin"],
        dependency: f.pkg,
      },
    }
  },
)

const themeItem = {
  name: "theme",
  type: "registry:style",
  title: "Theme",
  description: "Design tokens: colour, type, radius, elevation and motion.",
  dependencies: ["tw-animate-css", "cn"],
  registryDependencies: fonts.map((f) => itemUrl(f.name)),
  cssVars: { theme, light: { ...root, ...light, ...effects.light }, dark: { ...dark, ...effects.dark } },
  css: {
    "@layer base": toRegistryCss(base),
    ...Object.fromEntries(Object.entries(utilities).map(([k, v]) => [`@utility ${k}`, v])),
  },
}

const UI_DIR = "src/components/ui"
const IGNORED_DEPS = new Set(["react", "react-dom"])
const componentItems = readdirSync(path.join(ROOT, UI_DIR))
  .filter((f) => f.endsWith(".tsx"))
  .sort()
  .map((file) => {
    const name = file.replace(/\.tsx$/, "")
    const src = readFileSync(path.join(ROOT, UI_DIR, file), "utf8")
    const imports = [...src.matchAll(/from\s+["']([^"']+)["']/g)].map((m) => m[1])
    const dependencies = new Set<string>()
    const registryDependencies = new Set<string>([itemUrl("theme")])
    const hookFiles: { path: string; type: string }[] = []
    for (const spec of imports) {
      if (spec.startsWith("@/components/ui/")) {
        registryDependencies.add(itemUrl(spec.slice("@/components/ui/".length)))
      } else if (spec.startsWith("@/hooks/")) {
        // Ship local hooks (e.g. use-mobile for Sidebar) alongside the component.
        hookFiles.push({ path: `src/hooks/${spec.slice("@/hooks/".length)}.ts`, type: "registry:hook" })
      } else if (!spec.startsWith(".") && !spec.startsWith("@/")) {
        const pkg = spec.startsWith("@") ? spec.split("/").slice(0, 2).join("/") : spec.split("/")[0]
        if (!IGNORED_DEPS.has(pkg)) dependencies.add(pkg)
      }
    }
    return {
      name,
      type: "registry:ui",
      title: name.replace(/(^|-)(\w)/g, (_, s, c) => (s ? " " : "") + c.toUpperCase()),
      dependencies: [...dependencies].sort(),
      registryDependencies: [...registryDependencies],
      files: [{ path: `${UI_DIR}/${file}`, type: "registry:ui" }, ...hookFiles],
    }
  })

const registry = {
  $schema: "https://ui.shadcn.com/schema/registry.json",
  name: REGISTRY_NAME,
  homepage: REGISTRY_URL.replace(/\/r$/, ""),
  items: [themeItem, ...fonts, ...componentItems],
}
writeFileSync(path.join(ROOT, "registry.json"), JSON.stringify(registry, null, 2) + "\n")

console.log(
  `tokens [${brand.name}]: ${lightKeys.length} semantic × 2 themes, ${Object.keys(root).length} brand vars → src/styles/tokens.css`,
)
console.log(`registry: ${registry.items.length} items → registry.json (${REGISTRY_URL})`)
