/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlocksIssueTrackerRouteImport } from './routes/blocks/issue-tracker'
import { Route as ComponentsAccordionRouteImport } from './routes/components/accordion'
import { Route as ComponentsAlertRouteImport } from './routes/components/alert'
import { Route as ComponentsAlertDialogRouteImport } from './routes/components/alert-dialog'
import { Route as ComponentsAvatarRouteImport } from './routes/components/avatar'
import { Route as ComponentsBadgeRouteImport } from './routes/components/badge'
import { Route as ComponentsBreadcrumbRouteImport } from './routes/components/breadcrumb'
import { Route as ComponentsButtonRouteImport } from './routes/components/button'
import { Route as ComponentsCalendarRouteImport } from './routes/components/calendar'
import { Route as ComponentsCardRouteImport } from './routes/components/card'
import { Route as ComponentsChartRouteImport } from './routes/components/chart'
import { Route as ComponentsCheckboxRouteImport } from './routes/components/checkbox'
import { Route as ComponentsCollapsibleRouteImport } from './routes/components/collapsible'
import { Route as ComponentsComboboxRouteImport } from './routes/components/combobox'
import { Route as ComponentsCommandRouteImport } from './routes/components/command'
import { Route as ComponentsContextMenuRouteImport } from './routes/components/context-menu'
import { Route as ComponentsDataTableRouteImport } from './routes/components/data-table'
import { Route as ComponentsDatePickerRouteImport } from './routes/components/date-picker'
import { Route as ComponentsDialogRouteImport } from './routes/components/dialog'
import { Route as ComponentsDropdownMenuRouteImport } from './routes/components/dropdown-menu'
import { Route as ComponentsFieldRouteImport } from './routes/components/field'
import { Route as ComponentsHoverCardRouteImport } from './routes/components/hover-card'
import { Route as ComponentsInputRouteImport } from './routes/components/input'
import { Route as ComponentsInputGroupRouteImport } from './routes/components/input-group'
import { Route as ComponentsInputOtpRouteImport } from './routes/components/input-otp'
import { Route as ComponentsKbdRouteImport } from './routes/components/kbd'
import { Route as ComponentsLabelRouteImport } from './routes/components/label'
import { Route as ComponentsNavigationMenuRouteImport } from './routes/components/navigation-menu'
import { Route as ComponentsPaginationRouteImport } from './routes/components/pagination'
import { Route as ComponentsPopoverRouteImport } from './routes/components/popover'
import { Route as ComponentsProgressRouteImport } from './routes/components/progress'
import { Route as ComponentsRadioGroupRouteImport } from './routes/components/radio-group'
import { Route as ComponentsSelectRouteImport } from './routes/components/select'
import { Route as ComponentsSeparatorRouteImport } from './routes/components/separator'
import { Route as ComponentsSheetRouteImport } from './routes/components/sheet'
import { Route as ComponentsSidebarRouteImport } from './routes/components/sidebar'
import { Route as ComponentsSkeletonRouteImport } from './routes/components/skeleton'
import { Route as ComponentsSliderRouteImport } from './routes/components/slider'
import { Route as ComponentsSpinnerRouteImport } from './routes/components/spinner'
import { Route as ComponentsSwitchRouteImport } from './routes/components/switch'
import { Route as ComponentsTableRouteImport } from './routes/components/table'
import { Route as ComponentsTabsRouteImport } from './routes/components/tabs'
import { Route as ComponentsTextareaRouteImport } from './routes/components/textarea'
import { Route as ComponentsToastRouteImport } from './routes/components/toast'
import { Route as ComponentsToggleRouteImport } from './routes/components/toggle'
import { Route as ComponentsToggleGroupRouteImport } from './routes/components/toggle-group'
import { Route as ComponentsTooltipRouteImport } from './routes/components/tooltip'
import { Route as FoundationsColourRouteImport } from './routes/foundations/colour'
import { Route as FoundationsMaterialsRouteImport } from './routes/foundations/materials'
import { Route as FoundationsMotionRouteImport } from './routes/foundations/motion'
import { Route as FoundationsShapeRouteImport } from './routes/foundations/shape'
import { Route as FoundationsTypographyRouteImport } from './routes/foundations/typography'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlocksIssueTrackerRoute = BlocksIssueTrackerRouteImport.update({
  id: '/blocks/issue-tracker',
  path: '/blocks/issue-tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsAccordionRoute = ComponentsAccordionRouteImport.update({
  id: '/components/accordion',
  path: '/components/accordion',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsAlertRoute = ComponentsAlertRouteImport.update({
  id: '/components/alert',
  path: '/components/alert',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsAlertDialogRoute = ComponentsAlertDialogRouteImport.update({
  id: '/components/alert-dialog',
  path: '/components/alert-dialog',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsAvatarRoute = ComponentsAvatarRouteImport.update({
  id: '/components/avatar',
  path: '/components/avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsBadgeRoute = ComponentsBadgeRouteImport.update({
  id: '/components/badge',
  path: '/components/badge',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsBreadcrumbRoute = ComponentsBreadcrumbRouteImport.update({
  id: '/components/breadcrumb',
  path: '/components/breadcrumb',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsButtonRoute = ComponentsButtonRouteImport.update({
  id: '/components/button',
  path: '/components/button',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsCalendarRoute = ComponentsCalendarRouteImport.update({
  id: '/components/calendar',
  path: '/components/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsCardRoute = ComponentsCardRouteImport.update({
  id: '/components/card',
  path: '/components/card',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsChartRoute = ComponentsChartRouteImport.update({
  id: '/components/chart',
  path: '/components/chart',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsCheckboxRoute = ComponentsCheckboxRouteImport.update({
  id: '/components/checkbox',
  path: '/components/checkbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsCollapsibleRoute = ComponentsCollapsibleRouteImport.update({
  id: '/components/collapsible',
  path: '/components/collapsible',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsComboboxRoute = ComponentsComboboxRouteImport.update({
  id: '/components/combobox',
  path: '/components/combobox',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsCommandRoute = ComponentsCommandRouteImport.update({
  id: '/components/command',
  path: '/components/command',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsContextMenuRoute = ComponentsContextMenuRouteImport.update({
  id: '/components/context-menu',
  path: '/components/context-menu',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsDataTableRoute = ComponentsDataTableRouteImport.update({
  id: '/components/data-table',
  path: '/components/data-table',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsDatePickerRoute = ComponentsDatePickerRouteImport.update({
  id: '/components/date-picker',
  path: '/components/date-picker',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsDialogRoute = ComponentsDialogRouteImport.update({
  id: '/components/dialog',
  path: '/components/dialog',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsDropdownMenuRoute = ComponentsDropdownMenuRouteImport.update({
  id: '/components/dropdown-menu',
  path: '/components/dropdown-menu',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsFieldRoute = ComponentsFieldRouteImport.update({
  id: '/components/field',
  path: '/components/field',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsHoverCardRoute = ComponentsHoverCardRouteImport.update({
  id: '/components/hover-card',
  path: '/components/hover-card',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsInputRoute = ComponentsInputRouteImport.update({
  id: '/components/input',
  path: '/components/input',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsInputGroupRoute = ComponentsInputGroupRouteImport.update({
  id: '/components/input-group',
  path: '/components/input-group',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsInputOtpRoute = ComponentsInputOtpRouteImport.update({
  id: '/components/input-otp',
  path: '/components/input-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsKbdRoute = ComponentsKbdRouteImport.update({
  id: '/components/kbd',
  path: '/components/kbd',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsLabelRoute = ComponentsLabelRouteImport.update({
  id: '/components/label',
  path: '/components/label',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsNavigationMenuRoute =
  ComponentsNavigationMenuRouteImport.update({
    id: '/components/navigation-menu',
    path: '/components/navigation-menu',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComponentsPaginationRoute = ComponentsPaginationRouteImport.update({
  id: '/components/pagination',
  path: '/components/pagination',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsPopoverRoute = ComponentsPopoverRouteImport.update({
  id: '/components/popover',
  path: '/components/popover',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsProgressRoute = ComponentsProgressRouteImport.update({
  id: '/components/progress',
  path: '/components/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsRadioGroupRoute = ComponentsRadioGroupRouteImport.update({
  id: '/components/radio-group',
  path: '/components/radio-group',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsSelectRoute = ComponentsSelectRouteImport.update({
  id: '/components/select',
  path: '/components/select',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsSeparatorRoute = ComponentsSeparatorRouteImport.update({
  id: '/components/separator',
  path: '/components/separator',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsSheetRoute = ComponentsSheetRouteImport.update({
  id: '/components/sheet',
  path: '/components/sheet',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsSidebarRoute = ComponentsSidebarRouteImport.update({
  id: '/components/sidebar',
  path: '/components/sidebar',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsSkeletonRoute = ComponentsSkeletonRouteImport.update({
  id: '/components/skeleton',
  path: '/components/skeleton',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsSliderRoute = ComponentsSliderRouteImport.update({
  id: '/components/slider',
  path: '/components/slider',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsSpinnerRoute = ComponentsSpinnerRouteImport.update({
  id: '/components/spinner',
  path: '/components/spinner',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsSwitchRoute = ComponentsSwitchRouteImport.update({
  id: '/components/switch',
  path: '/components/switch',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsTableRoute = ComponentsTableRouteImport.update({
  id: '/components/table',
  path: '/components/table',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsTabsRoute = ComponentsTabsRouteImport.update({
  id: '/components/tabs',
  path: '/components/tabs',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsTextareaRoute = ComponentsTextareaRouteImport.update({
  id: '/components/textarea',
  path: '/components/textarea',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsToastRoute = ComponentsToastRouteImport.update({
  id: '/components/toast',
  path: '/components/toast',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsToggleRoute = ComponentsToggleRouteImport.update({
  id: '/components/toggle',
  path: '/components/toggle',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsToggleGroupRoute = ComponentsToggleGroupRouteImport.update({
  id: '/components/toggle-group',
  path: '/components/toggle-group',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsTooltipRoute = ComponentsTooltipRouteImport.update({
  id: '/components/tooltip',
  path: '/components/tooltip',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundationsColourRoute = FoundationsColourRouteImport.update({
  id: '/foundations/colour',
  path: '/foundations/colour',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundationsMaterialsRoute = FoundationsMaterialsRouteImport.update({
  id: '/foundations/materials',
  path: '/foundations/materials',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundationsMotionRoute = FoundationsMotionRouteImport.update({
  id: '/foundations/motion',
  path: '/foundations/motion',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundationsShapeRoute = FoundationsShapeRouteImport.update({
  id: '/foundations/shape',
  path: '/foundations/shape',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundationsTypographyRoute = FoundationsTypographyRouteImport.update({
  id: '/foundations/typography',
  path: '/foundations/typography',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blocks/issue-tracker': typeof BlocksIssueTrackerRoute
  '/components/accordion': typeof ComponentsAccordionRoute
  '/components/alert': typeof ComponentsAlertRoute
  '/components/alert-dialog': typeof ComponentsAlertDialogRoute
  '/components/avatar': typeof ComponentsAvatarRoute
  '/components/badge': typeof ComponentsBadgeRoute
  '/components/breadcrumb': typeof ComponentsBreadcrumbRoute
  '/components/button': typeof ComponentsButtonRoute
  '/components/calendar': typeof ComponentsCalendarRoute
  '/components/card': typeof ComponentsCardRoute
  '/components/chart': typeof ComponentsChartRoute
  '/components/checkbox': typeof ComponentsCheckboxRoute
  '/components/collapsible': typeof ComponentsCollapsibleRoute
  '/components/combobox': typeof ComponentsComboboxRoute
  '/components/command': typeof ComponentsCommandRoute
  '/components/context-menu': typeof ComponentsContextMenuRoute
  '/components/data-table': typeof ComponentsDataTableRoute
  '/components/date-picker': typeof ComponentsDatePickerRoute
  '/components/dialog': typeof ComponentsDialogRoute
  '/components/dropdown-menu': typeof ComponentsDropdownMenuRoute
  '/components/field': typeof ComponentsFieldRoute
  '/components/hover-card': typeof ComponentsHoverCardRoute
  '/components/input': typeof ComponentsInputRoute
  '/components/input-group': typeof ComponentsInputGroupRoute
  '/components/input-otp': typeof ComponentsInputOtpRoute
  '/components/kbd': typeof ComponentsKbdRoute
  '/components/label': typeof ComponentsLabelRoute
  '/components/navigation-menu': typeof ComponentsNavigationMenuRoute
  '/components/pagination': typeof ComponentsPaginationRoute
  '/components/popover': typeof ComponentsPopoverRoute
  '/components/progress': typeof ComponentsProgressRoute
  '/components/radio-group': typeof ComponentsRadioGroupRoute
  '/components/select': typeof ComponentsSelectRoute
  '/components/separator': typeof ComponentsSeparatorRoute
  '/components/sheet': typeof ComponentsSheetRoute
  '/components/sidebar': typeof ComponentsSidebarRoute
  '/components/skeleton': typeof ComponentsSkeletonRoute
  '/components/slider': typeof ComponentsSliderRoute
  '/components/spinner': typeof ComponentsSpinnerRoute
  '/components/switch': typeof ComponentsSwitchRoute
  '/components/table': typeof ComponentsTableRoute
  '/components/tabs': typeof ComponentsTabsRoute
  '/components/textarea': typeof ComponentsTextareaRoute
  '/components/toast': typeof ComponentsToastRoute
  '/components/toggle': typeof ComponentsToggleRoute
  '/components/toggle-group': typeof ComponentsToggleGroupRoute
  '/components/tooltip': typeof ComponentsTooltipRoute
  '/foundations/colour': typeof FoundationsColourRoute
  '/foundations/materials': typeof FoundationsMaterialsRoute
  '/foundations/motion': typeof FoundationsMotionRoute
  '/foundations/shape': typeof FoundationsShapeRoute
  '/foundations/typography': typeof FoundationsTypographyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blocks/issue-tracker': typeof BlocksIssueTrackerRoute
  '/components/accordion': typeof ComponentsAccordionRoute
  '/components/alert': typeof ComponentsAlertRoute
  '/components/alert-dialog': typeof ComponentsAlertDialogRoute
  '/components/avatar': typeof ComponentsAvatarRoute
  '/components/badge': typeof ComponentsBadgeRoute
  '/components/breadcrumb': typeof ComponentsBreadcrumbRoute
  '/components/button': typeof ComponentsButtonRoute
  '/components/calendar': typeof ComponentsCalendarRoute
  '/components/card': typeof ComponentsCardRoute
  '/components/chart': typeof ComponentsChartRoute
  '/components/checkbox': typeof ComponentsCheckboxRoute
  '/components/collapsible': typeof ComponentsCollapsibleRoute
  '/components/combobox': typeof ComponentsComboboxRoute
  '/components/command': typeof ComponentsCommandRoute
  '/components/context-menu': typeof ComponentsContextMenuRoute
  '/components/data-table': typeof ComponentsDataTableRoute
  '/components/date-picker': typeof ComponentsDatePickerRoute
  '/components/dialog': typeof ComponentsDialogRoute
  '/components/dropdown-menu': typeof ComponentsDropdownMenuRoute
  '/components/field': typeof ComponentsFieldRoute
  '/components/hover-card': typeof ComponentsHoverCardRoute
  '/components/input': typeof ComponentsInputRoute
  '/components/input-group': typeof ComponentsInputGroupRoute
  '/components/input-otp': typeof ComponentsInputOtpRoute
  '/components/kbd': typeof ComponentsKbdRoute
  '/components/label': typeof ComponentsLabelRoute
  '/components/navigation-menu': typeof ComponentsNavigationMenuRoute
  '/components/pagination': typeof ComponentsPaginationRoute
  '/components/popover': typeof ComponentsPopoverRoute
  '/components/progress': typeof ComponentsProgressRoute
  '/components/radio-group': typeof ComponentsRadioGroupRoute
  '/components/select': typeof ComponentsSelectRoute
  '/components/separator': typeof ComponentsSeparatorRoute
  '/components/sheet': typeof ComponentsSheetRoute
  '/components/sidebar': typeof ComponentsSidebarRoute
  '/components/skeleton': typeof ComponentsSkeletonRoute
  '/components/slider': typeof ComponentsSliderRoute
  '/components/spinner': typeof ComponentsSpinnerRoute
  '/components/switch': typeof ComponentsSwitchRoute
  '/components/table': typeof ComponentsTableRoute
  '/components/tabs': typeof ComponentsTabsRoute
  '/components/textarea': typeof ComponentsTextareaRoute
  '/components/toast': typeof ComponentsToastRoute
  '/components/toggle': typeof ComponentsToggleRoute
  '/components/toggle-group': typeof ComponentsToggleGroupRoute
  '/components/tooltip': typeof ComponentsTooltipRoute
  '/foundations/colour': typeof FoundationsColourRoute
  '/foundations/materials': typeof FoundationsMaterialsRoute
  '/foundations/motion': typeof FoundationsMotionRoute
  '/foundations/shape': typeof FoundationsShapeRoute
  '/foundations/typography': typeof FoundationsTypographyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blocks/issue-tracker': typeof BlocksIssueTrackerRoute
  '/components/accordion': typeof ComponentsAccordionRoute
  '/components/alert': typeof ComponentsAlertRoute
  '/components/alert-dialog': typeof ComponentsAlertDialogRoute
  '/components/avatar': typeof ComponentsAvatarRoute
  '/components/badge': typeof ComponentsBadgeRoute
  '/components/breadcrumb': typeof ComponentsBreadcrumbRoute
  '/components/button': typeof ComponentsButtonRoute
  '/components/calendar': typeof ComponentsCalendarRoute
  '/components/card': typeof ComponentsCardRoute
  '/components/chart': typeof ComponentsChartRoute
  '/components/checkbox': typeof ComponentsCheckboxRoute
  '/components/collapsible': typeof ComponentsCollapsibleRoute
  '/components/combobox': typeof ComponentsComboboxRoute
  '/components/command': typeof ComponentsCommandRoute
  '/components/context-menu': typeof ComponentsContextMenuRoute
  '/components/data-table': typeof ComponentsDataTableRoute
  '/components/date-picker': typeof ComponentsDatePickerRoute
  '/components/dialog': typeof ComponentsDialogRoute
  '/components/dropdown-menu': typeof ComponentsDropdownMenuRoute
  '/components/field': typeof ComponentsFieldRoute
  '/components/hover-card': typeof ComponentsHoverCardRoute
  '/components/input': typeof ComponentsInputRoute
  '/components/input-group': typeof ComponentsInputGroupRoute
  '/components/input-otp': typeof ComponentsInputOtpRoute
  '/components/kbd': typeof ComponentsKbdRoute
  '/components/label': typeof ComponentsLabelRoute
  '/components/navigation-menu': typeof ComponentsNavigationMenuRoute
  '/components/pagination': typeof ComponentsPaginationRoute
  '/components/popover': typeof ComponentsPopoverRoute
  '/components/progress': typeof ComponentsProgressRoute
  '/components/radio-group': typeof ComponentsRadioGroupRoute
  '/components/select': typeof ComponentsSelectRoute
  '/components/separator': typeof ComponentsSeparatorRoute
  '/components/sheet': typeof ComponentsSheetRoute
  '/components/sidebar': typeof ComponentsSidebarRoute
  '/components/skeleton': typeof ComponentsSkeletonRoute
  '/components/slider': typeof ComponentsSliderRoute
  '/components/spinner': typeof ComponentsSpinnerRoute
  '/components/switch': typeof ComponentsSwitchRoute
  '/components/table': typeof ComponentsTableRoute
  '/components/tabs': typeof ComponentsTabsRoute
  '/components/textarea': typeof ComponentsTextareaRoute
  '/components/toast': typeof ComponentsToastRoute
  '/components/toggle': typeof ComponentsToggleRoute
  '/components/toggle-group': typeof ComponentsToggleGroupRoute
  '/components/tooltip': typeof ComponentsTooltipRoute
  '/foundations/colour': typeof FoundationsColourRoute
  '/foundations/materials': typeof FoundationsMaterialsRoute
  '/foundations/motion': typeof FoundationsMotionRoute
  '/foundations/shape': typeof FoundationsShapeRoute
  '/foundations/typography': typeof FoundationsTypographyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blocks/issue-tracker'
    | '/components/accordion'
    | '/components/alert'
    | '/components/alert-dialog'
    | '/components/avatar'
    | '/components/badge'
    | '/components/breadcrumb'
    | '/components/button'
    | '/components/calendar'
    | '/components/card'
    | '/components/chart'
    | '/components/checkbox'
    | '/components/collapsible'
    | '/components/combobox'
    | '/components/command'
    | '/components/context-menu'
    | '/components/data-table'
    | '/components/date-picker'
    | '/components/dialog'
    | '/components/dropdown-menu'
    | '/components/field'
    | '/components/hover-card'
    | '/components/input'
    | '/components/input-group'
    | '/components/input-otp'
    | '/components/kbd'
    | '/components/label'
    | '/components/navigation-menu'
    | '/components/pagination'
    | '/components/popover'
    | '/components/progress'
    | '/components/radio-group'
    | '/components/select'
    | '/components/separator'
    | '/components/sheet'
    | '/components/sidebar'
    | '/components/skeleton'
    | '/components/slider'
    | '/components/spinner'
    | '/components/switch'
    | '/components/table'
    | '/components/tabs'
    | '/components/textarea'
    | '/components/toast'
    | '/components/toggle'
    | '/components/toggle-group'
    | '/components/tooltip'
    | '/foundations/colour'
    | '/foundations/materials'
    | '/foundations/motion'
    | '/foundations/shape'
    | '/foundations/typography'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blocks/issue-tracker'
    | '/components/accordion'
    | '/components/alert'
    | '/components/alert-dialog'
    | '/components/avatar'
    | '/components/badge'
    | '/components/breadcrumb'
    | '/components/button'
    | '/components/calendar'
    | '/components/card'
    | '/components/chart'
    | '/components/checkbox'
    | '/components/collapsible'
    | '/components/combobox'
    | '/components/command'
    | '/components/context-menu'
    | '/components/data-table'
    | '/components/date-picker'
    | '/components/dialog'
    | '/components/dropdown-menu'
    | '/components/field'
    | '/components/hover-card'
    | '/components/input'
    | '/components/input-group'
    | '/components/input-otp'
    | '/components/kbd'
    | '/components/label'
    | '/components/navigation-menu'
    | '/components/pagination'
    | '/components/popover'
    | '/components/progress'
    | '/components/radio-group'
    | '/components/select'
    | '/components/separator'
    | '/components/sheet'
    | '/components/sidebar'
    | '/components/skeleton'
    | '/components/slider'
    | '/components/spinner'
    | '/components/switch'
    | '/components/table'
    | '/components/tabs'
    | '/components/textarea'
    | '/components/toast'
    | '/components/toggle'
    | '/components/toggle-group'
    | '/components/tooltip'
    | '/foundations/colour'
    | '/foundations/materials'
    | '/foundations/motion'
    | '/foundations/shape'
    | '/foundations/typography'
  id:
    | '__root__'
    | '/'
    | '/blocks/issue-tracker'
    | '/components/accordion'
    | '/components/alert'
    | '/components/alert-dialog'
    | '/components/avatar'
    | '/components/badge'
    | '/components/breadcrumb'
    | '/components/button'
    | '/components/calendar'
    | '/components/card'
    | '/components/chart'
    | '/components/checkbox'
    | '/components/collapsible'
    | '/components/combobox'
    | '/components/command'
    | '/components/context-menu'
    | '/components/data-table'
    | '/components/date-picker'
    | '/components/dialog'
    | '/components/dropdown-menu'
    | '/components/field'
    | '/components/hover-card'
    | '/components/input'
    | '/components/input-group'
    | '/components/input-otp'
    | '/components/kbd'
    | '/components/label'
    | '/components/navigation-menu'
    | '/components/pagination'
    | '/components/popover'
    | '/components/progress'
    | '/components/radio-group'
    | '/components/select'
    | '/components/separator'
    | '/components/sheet'
    | '/components/sidebar'
    | '/components/skeleton'
    | '/components/slider'
    | '/components/spinner'
    | '/components/switch'
    | '/components/table'
    | '/components/tabs'
    | '/components/textarea'
    | '/components/toast'
    | '/components/toggle'
    | '/components/toggle-group'
    | '/components/tooltip'
    | '/foundations/colour'
    | '/foundations/materials'
    | '/foundations/motion'
    | '/foundations/shape'
    | '/foundations/typography'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlocksIssueTrackerRoute: typeof BlocksIssueTrackerRoute
  ComponentsAccordionRoute: typeof ComponentsAccordionRoute
  ComponentsAlertRoute: typeof ComponentsAlertRoute
  ComponentsAlertDialogRoute: typeof ComponentsAlertDialogRoute
  ComponentsAvatarRoute: typeof ComponentsAvatarRoute
  ComponentsBadgeRoute: typeof ComponentsBadgeRoute
  ComponentsBreadcrumbRoute: typeof ComponentsBreadcrumbRoute
  ComponentsButtonRoute: typeof ComponentsButtonRoute
  ComponentsCalendarRoute: typeof ComponentsCalendarRoute
  ComponentsCardRoute: typeof ComponentsCardRoute
  ComponentsChartRoute: typeof ComponentsChartRoute
  ComponentsCheckboxRoute: typeof ComponentsCheckboxRoute
  ComponentsCollapsibleRoute: typeof ComponentsCollapsibleRoute
  ComponentsComboboxRoute: typeof ComponentsComboboxRoute
  ComponentsCommandRoute: typeof ComponentsCommandRoute
  ComponentsContextMenuRoute: typeof ComponentsContextMenuRoute
  ComponentsDataTableRoute: typeof ComponentsDataTableRoute
  ComponentsDatePickerRoute: typeof ComponentsDatePickerRoute
  ComponentsDialogRoute: typeof ComponentsDialogRoute
  ComponentsDropdownMenuRoute: typeof ComponentsDropdownMenuRoute
  ComponentsFieldRoute: typeof ComponentsFieldRoute
  ComponentsHoverCardRoute: typeof ComponentsHoverCardRoute
  ComponentsInputRoute: typeof ComponentsInputRoute
  ComponentsInputGroupRoute: typeof ComponentsInputGroupRoute
  ComponentsInputOtpRoute: typeof ComponentsInputOtpRoute
  ComponentsKbdRoute: typeof ComponentsKbdRoute
  ComponentsLabelRoute: typeof ComponentsLabelRoute
  ComponentsNavigationMenuRoute: typeof ComponentsNavigationMenuRoute
  ComponentsPaginationRoute: typeof ComponentsPaginationRoute
  ComponentsPopoverRoute: typeof ComponentsPopoverRoute
  ComponentsProgressRoute: typeof ComponentsProgressRoute
  ComponentsRadioGroupRoute: typeof ComponentsRadioGroupRoute
  ComponentsSelectRoute: typeof ComponentsSelectRoute
  ComponentsSeparatorRoute: typeof ComponentsSeparatorRoute
  ComponentsSheetRoute: typeof ComponentsSheetRoute
  ComponentsSidebarRoute: typeof ComponentsSidebarRoute
  ComponentsSkeletonRoute: typeof ComponentsSkeletonRoute
  ComponentsSliderRoute: typeof ComponentsSliderRoute
  ComponentsSpinnerRoute: typeof ComponentsSpinnerRoute
  ComponentsSwitchRoute: typeof ComponentsSwitchRoute
  ComponentsTableRoute: typeof ComponentsTableRoute
  ComponentsTabsRoute: typeof ComponentsTabsRoute
  ComponentsTextareaRoute: typeof ComponentsTextareaRoute
  ComponentsToastRoute: typeof ComponentsToastRoute
  ComponentsToggleRoute: typeof ComponentsToggleRoute
  ComponentsToggleGroupRoute: typeof ComponentsToggleGroupRoute
  ComponentsTooltipRoute: typeof ComponentsTooltipRoute
  FoundationsColourRoute: typeof FoundationsColourRoute
  FoundationsMaterialsRoute: typeof FoundationsMaterialsRoute
  FoundationsMotionRoute: typeof FoundationsMotionRoute
  FoundationsShapeRoute: typeof FoundationsShapeRoute
  FoundationsTypographyRoute: typeof FoundationsTypographyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocks/issue-tracker': {
      id: '/blocks/issue-tracker'
      path: '/blocks/issue-tracker'
      fullPath: '/blocks/issue-tracker'
      preLoaderRoute: typeof BlocksIssueTrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/accordion': {
      id: '/components/accordion'
      path: '/components/accordion'
      fullPath: '/components/accordion'
      preLoaderRoute: typeof ComponentsAccordionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/alert': {
      id: '/components/alert'
      path: '/components/alert'
      fullPath: '/components/alert'
      preLoaderRoute: typeof ComponentsAlertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/alert-dialog': {
      id: '/components/alert-dialog'
      path: '/components/alert-dialog'
      fullPath: '/components/alert-dialog'
      preLoaderRoute: typeof ComponentsAlertDialogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/avatar': {
      id: '/components/avatar'
      path: '/components/avatar'
      fullPath: '/components/avatar'
      preLoaderRoute: typeof ComponentsAvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/badge': {
      id: '/components/badge'
      path: '/components/badge'
      fullPath: '/components/badge'
      preLoaderRoute: typeof ComponentsBadgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/breadcrumb': {
      id: '/components/breadcrumb'
      path: '/components/breadcrumb'
      fullPath: '/components/breadcrumb'
      preLoaderRoute: typeof ComponentsBreadcrumbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/button': {
      id: '/components/button'
      path: '/components/button'
      fullPath: '/components/button'
      preLoaderRoute: typeof ComponentsButtonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/calendar': {
      id: '/components/calendar'
      path: '/components/calendar'
      fullPath: '/components/calendar'
      preLoaderRoute: typeof ComponentsCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/card': {
      id: '/components/card'
      path: '/components/card'
      fullPath: '/components/card'
      preLoaderRoute: typeof ComponentsCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/chart': {
      id: '/components/chart'
      path: '/components/chart'
      fullPath: '/components/chart'
      preLoaderRoute: typeof ComponentsChartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/checkbox': {
      id: '/components/checkbox'
      path: '/components/checkbox'
      fullPath: '/components/checkbox'
      preLoaderRoute: typeof ComponentsCheckboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/collapsible': {
      id: '/components/collapsible'
      path: '/components/collapsible'
      fullPath: '/components/collapsible'
      preLoaderRoute: typeof ComponentsCollapsibleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/combobox': {
      id: '/components/combobox'
      path: '/components/combobox'
      fullPath: '/components/combobox'
      preLoaderRoute: typeof ComponentsComboboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/command': {
      id: '/components/command'
      path: '/components/command'
      fullPath: '/components/command'
      preLoaderRoute: typeof ComponentsCommandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/context-menu': {
      id: '/components/context-menu'
      path: '/components/context-menu'
      fullPath: '/components/context-menu'
      preLoaderRoute: typeof ComponentsContextMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/data-table': {
      id: '/components/data-table'
      path: '/components/data-table'
      fullPath: '/components/data-table'
      preLoaderRoute: typeof ComponentsDataTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/date-picker': {
      id: '/components/date-picker'
      path: '/components/date-picker'
      fullPath: '/components/date-picker'
      preLoaderRoute: typeof ComponentsDatePickerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/dialog': {
      id: '/components/dialog'
      path: '/components/dialog'
      fullPath: '/components/dialog'
      preLoaderRoute: typeof ComponentsDialogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/dropdown-menu': {
      id: '/components/dropdown-menu'
      path: '/components/dropdown-menu'
      fullPath: '/components/dropdown-menu'
      preLoaderRoute: typeof ComponentsDropdownMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/field': {
      id: '/components/field'
      path: '/components/field'
      fullPath: '/components/field'
      preLoaderRoute: typeof ComponentsFieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/hover-card': {
      id: '/components/hover-card'
      path: '/components/hover-card'
      fullPath: '/components/hover-card'
      preLoaderRoute: typeof ComponentsHoverCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/input': {
      id: '/components/input'
      path: '/components/input'
      fullPath: '/components/input'
      preLoaderRoute: typeof ComponentsInputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/input-group': {
      id: '/components/input-group'
      path: '/components/input-group'
      fullPath: '/components/input-group'
      preLoaderRoute: typeof ComponentsInputGroupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/input-otp': {
      id: '/components/input-otp'
      path: '/components/input-otp'
      fullPath: '/components/input-otp'
      preLoaderRoute: typeof ComponentsInputOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/kbd': {
      id: '/components/kbd'
      path: '/components/kbd'
      fullPath: '/components/kbd'
      preLoaderRoute: typeof ComponentsKbdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/label': {
      id: '/components/label'
      path: '/components/label'
      fullPath: '/components/label'
      preLoaderRoute: typeof ComponentsLabelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/navigation-menu': {
      id: '/components/navigation-menu'
      path: '/components/navigation-menu'
      fullPath: '/components/navigation-menu'
      preLoaderRoute: typeof ComponentsNavigationMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/pagination': {
      id: '/components/pagination'
      path: '/components/pagination'
      fullPath: '/components/pagination'
      preLoaderRoute: typeof ComponentsPaginationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/popover': {
      id: '/components/popover'
      path: '/components/popover'
      fullPath: '/components/popover'
      preLoaderRoute: typeof ComponentsPopoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/progress': {
      id: '/components/progress'
      path: '/components/progress'
      fullPath: '/components/progress'
      preLoaderRoute: typeof ComponentsProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/radio-group': {
      id: '/components/radio-group'
      path: '/components/radio-group'
      fullPath: '/components/radio-group'
      preLoaderRoute: typeof ComponentsRadioGroupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/select': {
      id: '/components/select'
      path: '/components/select'
      fullPath: '/components/select'
      preLoaderRoute: typeof ComponentsSelectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/separator': {
      id: '/components/separator'
      path: '/components/separator'
      fullPath: '/components/separator'
      preLoaderRoute: typeof ComponentsSeparatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/sheet': {
      id: '/components/sheet'
      path: '/components/sheet'
      fullPath: '/components/sheet'
      preLoaderRoute: typeof ComponentsSheetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/sidebar': {
      id: '/components/sidebar'
      path: '/components/sidebar'
      fullPath: '/components/sidebar'
      preLoaderRoute: typeof ComponentsSidebarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/skeleton': {
      id: '/components/skeleton'
      path: '/components/skeleton'
      fullPath: '/components/skeleton'
      preLoaderRoute: typeof ComponentsSkeletonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/slider': {
      id: '/components/slider'
      path: '/components/slider'
      fullPath: '/components/slider'
      preLoaderRoute: typeof ComponentsSliderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/spinner': {
      id: '/components/spinner'
      path: '/components/spinner'
      fullPath: '/components/spinner'
      preLoaderRoute: typeof ComponentsSpinnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/switch': {
      id: '/components/switch'
      path: '/components/switch'
      fullPath: '/components/switch'
      preLoaderRoute: typeof ComponentsSwitchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/table': {
      id: '/components/table'
      path: '/components/table'
      fullPath: '/components/table'
      preLoaderRoute: typeof ComponentsTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/tabs': {
      id: '/components/tabs'
      path: '/components/tabs'
      fullPath: '/components/tabs'
      preLoaderRoute: typeof ComponentsTabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/textarea': {
      id: '/components/textarea'
      path: '/components/textarea'
      fullPath: '/components/textarea'
      preLoaderRoute: typeof ComponentsTextareaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/toast': {
      id: '/components/toast'
      path: '/components/toast'
      fullPath: '/components/toast'
      preLoaderRoute: typeof ComponentsToastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/toggle': {
      id: '/components/toggle'
      path: '/components/toggle'
      fullPath: '/components/toggle'
      preLoaderRoute: typeof ComponentsToggleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/toggle-group': {
      id: '/components/toggle-group'
      path: '/components/toggle-group'
      fullPath: '/components/toggle-group'
      preLoaderRoute: typeof ComponentsToggleGroupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/tooltip': {
      id: '/components/tooltip'
      path: '/components/tooltip'
      fullPath: '/components/tooltip'
      preLoaderRoute: typeof ComponentsTooltipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foundations/colour': {
      id: '/foundations/colour'
      path: '/foundations/colour'
      fullPath: '/foundations/colour'
      preLoaderRoute: typeof FoundationsColourRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foundations/materials': {
      id: '/foundations/materials'
      path: '/foundations/materials'
      fullPath: '/foundations/materials'
      preLoaderRoute: typeof FoundationsMaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foundations/motion': {
      id: '/foundations/motion'
      path: '/foundations/motion'
      fullPath: '/foundations/motion'
      preLoaderRoute: typeof FoundationsMotionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foundations/shape': {
      id: '/foundations/shape'
      path: '/foundations/shape'
      fullPath: '/foundations/shape'
      preLoaderRoute: typeof FoundationsShapeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foundations/typography': {
      id: '/foundations/typography'
      path: '/foundations/typography'
      fullPath: '/foundations/typography'
      preLoaderRoute: typeof FoundationsTypographyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlocksIssueTrackerRoute: BlocksIssueTrackerRoute,
  ComponentsAccordionRoute: ComponentsAccordionRoute,
  ComponentsAlertRoute: ComponentsAlertRoute,
  ComponentsAlertDialogRoute: ComponentsAlertDialogRoute,
  ComponentsAvatarRoute: ComponentsAvatarRoute,
  ComponentsBadgeRoute: ComponentsBadgeRoute,
  ComponentsBreadcrumbRoute: ComponentsBreadcrumbRoute,
  ComponentsButtonRoute: ComponentsButtonRoute,
  ComponentsCalendarRoute: ComponentsCalendarRoute,
  ComponentsCardRoute: ComponentsCardRoute,
  ComponentsChartRoute: ComponentsChartRoute,
  ComponentsCheckboxRoute: ComponentsCheckboxRoute,
  ComponentsCollapsibleRoute: ComponentsCollapsibleRoute,
  ComponentsComboboxRoute: ComponentsComboboxRoute,
  ComponentsCommandRoute: ComponentsCommandRoute,
  ComponentsContextMenuRoute: ComponentsContextMenuRoute,
  ComponentsDataTableRoute: ComponentsDataTableRoute,
  ComponentsDatePickerRoute: ComponentsDatePickerRoute,
  ComponentsDialogRoute: ComponentsDialogRoute,
  ComponentsDropdownMenuRoute: ComponentsDropdownMenuRoute,
  ComponentsFieldRoute: ComponentsFieldRoute,
  ComponentsHoverCardRoute: ComponentsHoverCardRoute,
  ComponentsInputRoute: ComponentsInputRoute,
  ComponentsInputGroupRoute: ComponentsInputGroupRoute,
  ComponentsInputOtpRoute: ComponentsInputOtpRoute,
  ComponentsKbdRoute: ComponentsKbdRoute,
  ComponentsLabelRoute: ComponentsLabelRoute,
  ComponentsNavigationMenuRoute: ComponentsNavigationMenuRoute,
  ComponentsPaginationRoute: ComponentsPaginationRoute,
  ComponentsPopoverRoute: ComponentsPopoverRoute,
  ComponentsProgressRoute: ComponentsProgressRoute,
  ComponentsRadioGroupRoute: ComponentsRadioGroupRoute,
  ComponentsSelectRoute: ComponentsSelectRoute,
  ComponentsSeparatorRoute: ComponentsSeparatorRoute,
  ComponentsSheetRoute: ComponentsSheetRoute,
  ComponentsSidebarRoute: ComponentsSidebarRoute,
  ComponentsSkeletonRoute: ComponentsSkeletonRoute,
  ComponentsSliderRoute: ComponentsSliderRoute,
  ComponentsSpinnerRoute: ComponentsSpinnerRoute,
  ComponentsSwitchRoute: ComponentsSwitchRoute,
  ComponentsTableRoute: ComponentsTableRoute,
  ComponentsTabsRoute: ComponentsTabsRoute,
  ComponentsTextareaRoute: ComponentsTextareaRoute,
  ComponentsToastRoute: ComponentsToastRoute,
  ComponentsToggleRoute: ComponentsToggleRoute,
  ComponentsToggleGroupRoute: ComponentsToggleGroupRoute,
  ComponentsTooltipRoute: ComponentsTooltipRoute,
  FoundationsColourRoute: FoundationsColourRoute,
  FoundationsMaterialsRoute: FoundationsMaterialsRoute,
  FoundationsMotionRoute: FoundationsMotionRoute,
  FoundationsShapeRoute: FoundationsShapeRoute,
  FoundationsTypographyRoute: FoundationsTypographyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
